// Copyright KroNus Games 2025

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

/**
 *  ShGameplayTags
 */

namespace ShGameplayTags{
	namespace Attributes
	{
		namespace Primary
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Strength);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Toughness);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dexterity);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Intelligence);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Charisma);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Perception);
		}
		namespace Secondary
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Health);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxHealth);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Armor);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxArmor);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stamina);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxStamina);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(PowerCore);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxPowerCore);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mobility);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxMobility);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(CriticalChance);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(CriticalDamage);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(HealthRegen);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(StaminaRegen);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(PowerRegen);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hunger);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxHunger);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Thirst);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxThirst);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fatigue);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxFatigue);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stress);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxStress);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Contamination);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxContamination);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Processing);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxProcessing);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(LoyaltyProtocol);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxLoyaltyProtocol);
		}		
	}
	namespace InputTag
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(LeftMouseButton);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(RightMouseButton);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(KeyboardNumber1);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(KeyboardNumber2);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(KeyboardNumber3);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(KeyboardNumber4);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(KeyboardNumber5);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(KeyboardNumber6);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(KeyboardNumber7);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(KeyboardNumber8);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(KeyboardNumber9);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(KeyboardNumber10);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(KeyboardNumber11);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(KeyboardNumber12);
	}
	namespace Data
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(HealAmount);
	}
};
